issue 397 KMK and DSK wrt card re-issuance
usnistgov/FIPS201 pull request #616
Opened 2021-05-07 18:02 UTC by hferraio

closes #397

2021-05-12 16:49 UTC, jimfenton requested changes
Minor tweak, thought direct normative language should be used here.

2021-05-12 16:49 UTC, jimfenton commented on _FIPS201/requirements.md
> +corresponding certificates **SHALL** be populated with the new FASC-N and card UUID. For cardholders with government-issued email account, the digital signature and key management keys and associated
```suggestion
corresponding certificates **SHALL** be populated with the new FASC-N and card UUID. For cardholders with government-issued email accounts, the digital signature and key management keys and associated certificates **SHALL** be populated. A new digital signature key and associated certificate **SHALL** be generated on the new PIV card, while 
```

2021-05-13 16:23 UTC, regenscheid commented on _FIPS201/requirements.md
> +corresponding certificates **SHALL** be populated with the new FASC-N and card UUID. For cardholders with government-issued email account, the digital signature and key management keys and associated
Agree with Jim's edits

2021-05-13 16:24 UTC, regenscheid requested changes
Agree with Jim's edits.

2021-05-13 17:36 UTC, merged