OCC for maintenance.md
usnistgov/FIPS201 pull request #623
Opened 2021-05-18 17:50 UTC by hferraio

closes #395 
closes #401 
closes #584

2021-05-19 18:24 UTC, jimfenton requested changes
It looks like this puts a normative requirement in footnotes, which we're trying to avoid.

2021-05-19 18:24 UTC, jimfenton commented on _FIPS201/requirements.md
> +[^OCCorBIO]: BIO-A or OCC-AUTH authentication mechanism is performed when using the PIV Card for biometric  verification.
But not BIO then, right? That makes this a normative requirement, and should be therefore inline in text.

2021-05-19 18:24 UTC, jimfenton commented on _FIPS201/requirements.md
> +    [^OCCorBIOv2]: BIO-A or OCC-AUTH authentication mechanism is performed when using the PIV Card for biometric verification.
See above

2021-05-19 18:24 UTC, jimfenton commented on _FIPS201/requirements.md
> +     [^OCCorBIOv3]: BIO-A or OCC-AUTH authentication mechanism is performed when using the PIV Card for biometric verification.
See above

2021-05-27 17:17 UTC, gfiumara commented on _FIPS201/requirements.md
> +The issuer **SHALL** perform a biometric verification of the applicant to the biometric data records of the PIV enrollment record or to the biometric data records of the  PIV card and performing BIO-
```suggestion
The issuer **SHALL** perform a biometric verification of the applicant to the biometric data records of the PIV enrollment record or to the biometric data records of the  PIV Card and performing BIO-A  or OCC-AUTH authentication mechanism. Minimum accuracy requirements for
```

2021-05-27 17:19 UTC, gfiumara commented on _FIPS201/requirements.md
> +    records stored in the PIV enrollment record or when compared to the biometric data records on the PIV card and using BIO-A or OCC-AUTH authentication mechanism. In
```suggestion
    records stored in the PIV enrollment record or when compared to the biometric data records on the PIV Card and using BIO-A or OCC-AUTH authentication mechanism. In
```

2021-05-27 17:19 UTC, jricher commented on _FIPS201/requirements.md
> +
```suggestion

```

2021-05-27 17:20 UTC, jricher commented on _FIPS201/requirements.md
>  Issuer-operated kiosk
```suggestion

```

2021-05-27 17:21 UTC, jricher commented on _FIPS201/requirements.md
>  Issuer-operated kiosk
```suggestion

Issuer-operated kiosk
```

2021-05-27 17:21 UTC, gfiumara commented on _FIPS201/requirements.md
> +The issuer **SHALL** perform a biometric verification of the applicant to the biometric data records of the PIV enrollment record or to the biometric data records of the  PIV Card and performing BIO-
```suggestion
The issuer **SHALL** perform a biometric verification of the applicant to the biometric data records of the PIV enrollment record or to the biometric data records of the PIV Card using BIO-A or OCC-AUTH authentication mechanism. Minimum accuracy requirements for
```

2021-05-27 17:22 UTC, gfiumara commented on _FIPS201/requirements.md
> +    biometric characteristics elicit a positive biometric verification decision when compared to biometric data records stored in the PIV enrollment record or when compared to the biometric data reco
```suggestion
    biometric characteristics elicit a positive biometric verification decision when compared to biometric data records stored in the PIV enrollment record or when compared to the biometric data records on the PIV Card using the BIO-A or OCC-AUTH authentication mechanisms. In cases where a negative biometric verification decision is returned or the cardholder's biometric characteristics are not successfully acquired, the cardholder **SHALL** provide the PIV Card
```

2021-05-27 17:23 UTC, gfiumara commented on _FIPS201/requirements.md
> +    records stored in the PIV enrollment record or when compared to the biometric data records on the PIV Card and using BIO-A or OCC-AUTH authentication mechanism. In
```suggestion
    records stored in the PIV enrollment record or when compared to the biometric data records on the PIV Card and using the BIO-A or OCC-AUTH authentication mechanisms. In
```

2021-05-27 17:24 UTC, gfiumara commented on _FIPS201/requirements.md
> +
```suggestion
```

2021-05-27 17:24 UTC, gfiumara commented on _FIPS201/requirements.md
> +    The kiosk **MAY** be unattended while used for PIN reset operations.
```suggestion
    The kiosk **MAY** be unattended while used for PIN reset operations.
```

2021-05-27 17:24 UTC, merged