PIV federation SP number assigned
usnistgov/FIPS201 pull request #637
Opened 2021-06-07 14:30 UTC by hferraio

The number is SP 800-217.  I suggest a  title, but we can discuss if we want to change/edit title.

2021-06-10 17:20 UTC, jricher commented on _FIPS201/introduction.md
> +The requirements for issuing derived PIV credentials are specified in [[SP 800-157]](../_Appendix/references.md#ref-SP-800-157). Guidelines for the use of federations with PIV Credentials will be spe
```suggestion
The requirements for issuing derived PIV credentials are specified in [[SP 800-157]](../_Appendix/references.md#ref-SP-800-157). Guidelines for the use of federation with PIV Credentials will be specified in [[SP 800-217]](../_Appendix/references.md#ref-SP-800-217).
```

2021-06-10 17:20 UTC, jricher commented on _Appendix/references.md
> +*Guidelines for the Use of Personal Identity Verification (PIV) Credentials with Federations.*
```suggestion
*Guidelines for the Use of Personal Identity Verification (PIV) Credentials with Federation.*
```

2021-06-16 19:12 UTC, jimfenton requested changes
Small suggestion on the title: maybe, *Guidelines for the Federated Use of Personal Identity Verification (PIV) Credentials*

Want to include the expected DOI URL?

2021-06-16 19:12 UTC, jimfenton commented on _Appendix/references.md
> +[[SP 800-271]](references.md#ref-SP-800-217){:name="ref-SP-800-217"}
```suggestion
[[SP 800-217]](references.md#ref-SP-800-217){:name="ref-SP-800-217"} 
```

2021-06-17 17:19 UTC, regenscheid commented on _FIPS201/federation.md
> +Federation protocols allow a trusted IdP to assert a cardholder's identity to an RP across a network in a secure and verifiable fashion, even if the PIV Card or derived PIV credential has been issued
```suggestion
Federation protocols allow a trusted IdP to assert a cardholder's identity to an RP across a network in a secure and verifiable fashion, even if the PIV Card or derived PIV credential has been issued by another agency. The processes and requirements for federation systems are discussed in depth in [[SP 800-63C]](../_Appendix/references.md#ref-SP-800-63C). Additional guidelines for the use of federation with PIV Credentials will be specified in [[SP 800-217]](../_Appendix/references.md#ref-SP-800-217).
```

2021-06-17 17:23 UTC, merged