BIO-A or OCC-AUTH before in person PIN reset
usnistgov/FIPS201 pull request #638
Opened 2021-06-09 13:45 UTC by gfiumara

Closes #399.

2021-06-09 14:54 UTC, jricher approved these changes

2021-06-10 14:39 UTC, hferraio commented on _FIPS201/requirements.md
>      biometric characteristics elicit a positive biometric verification decision when compared to biometric data records stored in the PIV enrollment record or when compared to the biometric data reco
```suggestion
: When PIN reset is performed in person at the issuing facility, before
    resetting the PIV Card's PIN, the issuer **SHALL** first perform a biometric verification to ensure that the cardholder's
    biometric characteristics elicit a positive biometric verification decision when compared to biometric data records stored in the PIV enrollment record or when compared to the biometric data records on the PIV Card using OCC-AUTH authentication mechanisms. Alternatively, BIO-A authentication mechanism **MAY** be used as biometric verification after the card has been reset and while the card is in the operator's custody. The operator then hands the reset PIV Card to the cardholder. In cases where a negative biometric verification decision is returned or the cardholder's biometric characteristics are not successfully acquired, the cardholder **SHALL** provide the PIV Card
```
```suggestion
: When PIN reset is performed in person at the issuing facility, before
    resetting the PIV Card's PIN, the issuer **SHALL** first perform a biometric verification to ensure that the cardholder's
    biometric characteristics elicit a positive biometric verification decision when compared to biometric data records stored in the PIV enrollment record or when compared to the biometric data records on the PIV Card using the BIO-A or OCC-AUTH authentication mechanisms. In cases where a negative biometric verification decision is returned or the cardholder's biometric characteristics are not successfully acquired, the cardholder **SHALL** provide the PIV Card
```
```suggestion
: When PIN reset is performed in person at the issuing facility, before
    resetting the PIV Card's PIN, the issuer **SHALL** first perform a biometric verification to ensure that the cardholder's
    biometric characteristics elicit a positive biometric verification decision when compared to biometric data records stored in the PIV enrollment record or when compared to the biometric data records on the PIV Card using the BIO-A or OCC-AUTH authentication mechanisms. In cases where a negative biometric verification decision is returned or the cardholder's biometric characteristics are not successfully acquired, the cardholder **SHALL** provide the PIV Card
```
```suggestion
: When PIN reset is performed in person at the issuing facility, before
    resetting the PIV Card's PIN, the issuer **SHALL** first perform a biometric verification to ensure that the cardholder's
    biometric characteristics elicit a positive biometric verification decision when compared to biometric data records stored in the PIV enrollment record or when compared to the biometric data records on the PIV Card using the BIO-A or OCC-AUTH authentication mechanisms. In cases where a negative biometric verification decision is returned or the cardholder's biometric characteristics are not successfully acquired, the cardholder **SHALL** provide the PIV Card
```

2021-06-10 14:45 UTC, hferraio requested changes
BIO-A authentication mechanism is a two factor authentication method that first takes the PIN (verify), then releases the biometric on the card to be match off-card.  This method does not work on a card that is not reset yet.  Hence the changes.  WDYT?

2021-06-10 15:03 UTC, gfiumara commented
@hferraio Good point regarding BIO-A. IMO, this doesn't address what the requester asked for. We should potentially *not* allow BIO-A in this case? I will make the change to remove it _before_ now.

2021-06-10 15:58 UTC, hferraio commented
@gfiumara: Well, BIO-A and enrollment is the established method (as per FIPS 201-2). If we get rid of it, I am afraid we pull the rug underneath some implementation (hence my email to DoD and the MSO).  I thought our resolution was to allow both (OCC and BIO-A)?

2021-06-16 18:52 UTC, jimfenton commented
I'm guessing that the common case for PIN reset is forgotten PIN. BIO-A would not be usable in that case, so I don't think it would be pulling the rug out too seriously. But I suppose that someone might change their PIN because someone saw them entering it, and BIO-A would still be usable in that case, so I don't see a problem with allowing it.

2021-06-16 18:52 UTC, jimfenton reviewed
Generally like the changes, but see previous comment.

2021-06-17 14:52 UTC, hferraio commented
@jimfenton:  What has been possible until now ( per FIPS 201-2), is to reset the PIN **first** - now the BIO-A AuthN is available again since the PIN is unlocked.  Do BIO-A, then security guard/staff hands the card to the cardholder only after biometric comparison matched. (This is a in-person scenario we are discussing).

2021-06-17 17:40 UTC, jglosx3 commented
Closed

2021-06-17 17:41 UTC, jglosx3 commented
Closed because issue is declined

2021-07-01 14:46 UTC, gfiumara commented
Re-opening per request:
> The DoD performs the biometric comparison before the resetting of the PIN at this time.

2021-07-01 17:11 UTC, gfiumara commented on _FIPS201/requirements.md
> +    resetting the PIV Card's PIN, the issuer **SHALL** first perform a biometric verification to ensure that the cardholder's
```suggestion
    resetting the PIV Card's PIN, the issuer **SHALL** perform a biometric verification to ensure that the cardholder's
```

2021-07-01 17:11 UTC, gfiumara commented on _FIPS201/requirements.md
> +    biometric characteristics elicit a positive biometric verification decision when compared to biometric data records stored in the PIV enrollment record or when compared to the biometric data reco
```suggestion
    biometric characteristics elicit a positive biometric verification decision when compared to biometric data records stored in the PIV enrollment record or when compared to the biometric data records on the PIV Card using the BIO-A or OCC-AUTH authentication mechanisms. In cases where a negative biometric verification decision is returned or the cardholder's biometric characteristics are not successfully acquired, the cardholder **SHALL** provide the PIV Card
```

2021-07-01 17:12 UTC, closed without merging