Shall vs shall only
usnistgov/FIPS201 pull request #667
Opened 2021-06-25 20:35 UTC by hferraio

closes #317 
closes #315 
closes #314 
closes #316

2021-06-25 23:34 UTC, jimfenton requested changes
Suggestion for one place where we don't address all three interface types.

I'm puzzled, though, about why some of these allow contact and contactless but not virtual contact interfaces. Is there a rationale for that?

2021-06-25 23:34 UTC, jimfenton commented on _FIPS201/frontend.md
> +the PIV Card and **SHALL NOT** be available through the virtual contact interface of the PIV Card.
```suggestion
the PIV Card and **SHALL NOT** be available through the virtual contact and contactless interfaces of the PIV Card.
```

2021-06-28 14:46 UTC, hferraio commented on _FIPS201/frontend.md
> +present, the cryptographic operations that use the key management key **SHALL** available through
```suggestion
present, the cryptographic operations that use the key management key **SHALL** be available through 
```

2021-06-29 16:35 UTC, regenscheid commented on _FIPS201/frontend.md
> +authentication key **SHALL** be available through the contact and virtual contact interfaces of the
Being somewhat pedantic, should this be "SHALL" or should it instead be "MAY only"?

Or, perhaps more accurately, "SHALL be available over the contact interface and MAY be available over the virtual contact interface".  You wouldn't want a card that can't do PIV auth over the contact interface, but you can have one that doesn't have a VCI.

2021-06-29 17:17 UTC, regenscheid commented on _FIPS201/frontend.md
> +authentication key **SHALL** be available through the contact and virtual contact interfaces of the
```suggestion
authentication key **SHALL** be available through the contact interface and **MAY** additionally be available over the virtual contact interface of the
```

2021-06-29 17:17 UTC, regenscheid commented on _FIPS201/frontend.md
> +PIV Card and **SHALL NOT** be available through the contactless interface of the PIV Card.  Private key operations **MAY** be performed using an activated PIV Card without explicit
```suggestion
PIV Card. The PIV authentication key **SHALL NOT** be available through the contactless interface of the PIV Card.  Private key operations **MAY** be performed using an activated PIV Card without explicit
```

2021-06-29 17:19 UTC, regenscheid commented on _FIPS201/frontend.md
> +interfaces of the PIV Card and **SHALL NOT** be available through the contactless interface of the PIV Card. Private key operations **SHALL NOT** be performed without explicit user action,
```suggestion
that use the digital signature key **SHALL** be available through the contact interface and **MAY** additionally be available over the virtual contact
interface of the PIV Card. Operations that use the digital signature key **SHALL NOT** be available through the contactless interface of the PIV Card. Private key operations **SHALL NOT** be performed without explicit user action,
```

2021-06-29 17:24 UTC, regenscheid commented on _FIPS201/frontend.md
> +the contact and virtual contact interfaces of the PIV Card and **SHALL NOT** be available through the contactless interface of the PIV Card. Private key operations **MAY** be
```suggestion
present, the cryptographic operations that use the key management key **SHALL** be available through 
the contact interface and **MAY** additionally be available over the virtual contact interface of the PIV Card. Operations that use the key management key **SHALL NOT** be available through the contactless interface of the PIV Card. Private key operations **MAY** be
```

2021-06-29 17:27 UTC, merged