OCC AUTH privacy enhancing text
usnistgov/FIPS201 pull request #678
Opened 2021-07-01 20:59 UTC by hferraio

closes #355 #2

2021-07-02 11:02 UTC, gfiumara commented on _FIPS201/authentication.md
> +- privacy-enhancing as the OCC data is never exported and is stored and processed directly on the PIV card
Agree, but want to clarify. The image is captured and processed off-card, while only the comparison of a template takes place on the card. Not convinced this is the best rewording.

```suggestion
- privacy-enhancing, as the biometric template is both never exported and compared directly on the PIV Card 
```

2021-07-05 20:01 UTC, jimfenton requested changes
Couple editorial updates

2021-07-05 20:01 UTC, jimfenton commented on _FIPS201/authentication.md
> +The response includes information that allows the reader to authenticate the card. The cardholder PIN is not required for OCC-AUTH. The PIV Card **SHALL** include a mechanism to block this
```suggestion
The response includes information that allows the reader to authenticate the card. Entry of the cardholder PIN is not required for OCC-AUTH. The PIV Card **SHALL** include a mechanism to block this
```

2021-07-08 16:38 UTC, regenscheid approved these changes

2021-07-08 16:46 UTC, jimfenton approved these changes

2021-07-08 17:05 UTC, merged